In [127]:
import numpy as np
import pandas as pd

In [261]:
recipes = pd.read_json("recipes.json")
recipes = recipes.drop(columns=["image", "owner", "__v", "createdAt", "updatedAt", "updatedAT"])
recipes.head(1)

_id     title  \
0  6603aba5389c912a6b06549d  Panipuri   

                                         description  \
0   Rinse coriander and mint leaves in water and ...   

                                         ingredients vegNonVeg dishType  \
0  [{'ingredient_name': 'medium Onion', 'quantity...       Veg   Indian   

    category                                          favorites  
0  Fast food  [65d4c1b9e60cc7b970254148, 6605369a66779d49f72...

In [262]:
recipes["favorites"] = recipes["favorites"].apply(lambda x: len(x))
# print(recipes.head(2))
print(recipes.isnull().sum())
recipes.iloc[4]

def convert(obj):
    L = []
    for i in obj:
       L.append(i['ingredient_name'])
    return L

recipes['ingredients'] = recipes['ingredients'].apply(convert)
print(recipes.head(3))

_id            0
title          0
description    0
ingredients    0
vegNonVeg      0
dishType       0
category       0
favorites      0
dtype: int64
                        _id                title  \
0  6603aba5389c912a6b06549d             Panipuri   
1  6603aeb9389c912a6b065539  Chocolate Ice cream   
2  6603b054389c912a6b0655c2               Dabeli   

                                         description  \
0   Rinse coriander and mint leaves in water and ...   
1  Whip the cream till it is fluffy.\r\nCook coco...   
2  1.firstly, in a pan take 1 tsp coriander seeds...   

                                         ingredients vegNonVeg    dishType  \
0  [medium Onion, cup Sev, Mint Leaves, Chaat Mas...       Veg      Indian   
1  [Cocoa powder, whipping cream (cups), Milk(in ...       Veg      Indian   
2  [ aloo chana chat, dahi papdi chaat, chur chur...       Veg  Rajasthani   

    category  favorites  
0  Fast food          2  
1  Ice cream          3  
2  Fast food          2  


In [263]:
recipes["description"] = recipes["description"].apply(lambda x : x.split())
recipes["description"] = recipes["description"].apply(lambda x : [i.replace(" ", "") for i in x])
recipes["ingredients"] = recipes["ingredients"].apply(lambda x : [i.replace(" ", "") for i in x])
recipes["category"] = recipes["category"].apply(lambda x : x.replace(" ", ""))
recipes["dishType"] = recipes["dishType"].apply(lambda x : x.replace(" ", ""))
recipes.head(3)

_id                title  \
0  6603aba5389c912a6b06549d             Panipuri   
1  6603aeb9389c912a6b065539  Chocolate Ice cream   
2  6603b054389c912a6b0655c2               Dabeli   

                                         description  \
0  [Rinse, coriander, and, mint, leaves, in, wate...   
1  [Whip, the, cream, till, it, is, fluffy., Cook...   
2  [1.firstly,, in, a, pan, take, 1, tsp, coriand...   

                                         ingredients vegNonVeg    dishType  \
0  [mediumOnion, cupSev, MintLeaves, ChaatMasalaP...       Veg      Indian   
1  [Cocoapowder, whippingcream(cups), Milk(incup)...       Veg      Indian   
2  [aloochanachat, dahipapdichaat, churchurnaan, ...       Veg  Rajasthani   

   category  favorites  
0  Fastfood          2  
1  Icecream          3  
2  Fastfood          2

In [255]:
recipes['tags'] = recipes['description'] + recipes['ingredients']

In [256]:
new_df = recipes[["_id", "title", "tags", "dishType", "category", "vegNonVeg", "favorites"]]
new_df.head(2)

_id                title  \
0  6603aba5389c912a6b06549d             Panipuri   
1  6603aeb9389c912a6b065539  Chocolate Ice cream   

                                                tags dishType  category  \
0  [Rinse, coriander, and, mint, leaves, in, wate...   Indian  Fastfood   
1  [Whip, the, cream, till, it, is, fluffy., Cook...   Indian  Icecream   

  vegNonVeg  favorites  
0       Veg          2  
1       Veg          3

In [264]:
recipes["tags"] = (recipes["title"] + " " + 
                   recipes["description"].apply(lambda x: ' '.join(x)) + " " + 
                   recipes["description"].apply(lambda x: ' '.join(x)) + " " + 
                   recipes["vegNonVeg"] + " " + 
                   recipes["dishType"] + " " + 
                   recipes["category"])

In [266]:
recipes["tags"] = recipes["tags"].apply(lambda x : x.lower())

In [268]:
recipes.drop(columns=["title", "description", "ingredients", "vegNonVeg", "dishType", "category"], inplace=True)

In [269]:
recipes.head()

_id  favorites  \
0  6603aba5389c912a6b06549d          2   
1  6603aeb9389c912a6b065539          3   
2  6603b054389c912a6b0655c2          2   
3  6603b1d6389c912a6b0656dc          0   
4  6603b408389c912a6b065879          0   

                                                tags  
0  panipuri rinse coriander and mint leaves in wa...  
1  chocolate ice cream whip the cream till it is ...  
2  dabeli 1.firstly, in a pan take 1 tsp coriande...  
3  limbu _soda 1. place ice in a tall glass and f...  
4  pau bhaji  1. boil the veggies first and keep ...

In [270]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words='english') # 5000 most frequent words

In [272]:
vectors = cv.fit_transform(recipes['tags']).toarray()

In [273]:
print(vectors)
print(vectors[0])
cv.get_feature_names_out() # most frequent names

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10
  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0
  0  0  2  4  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  4  0  4  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0
  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  8  0  0  0  0  0  0  0  0  2  0  0  0  2  2  2  0  0  0  0  0
  0  0  0  2  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0  0  0
  0  2  0  0  0  0  1  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  2  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  2  2  4  0  0
  0 

array(['10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '1½',
       '20', '200', '2½', '30', '450f', '50', '_soda', 'aamchur', 'able',
       'absorb', 'according', 'achieved', 'add', 'added', 'adding',
       'adjust', 'agent', 'al', 'american', 'anise', 'apart', 'appam',
       'appe', 'applying', 'approx', 'approxx', 'arhar', 'aromas',
       'aromatic', 'asafoetida', 'aside', 'authenticity', 'away', 'bake',
       'baking', 'ball', 'balls', 'barfi', 'batches', 'batter', 'bay',
       'beans', 'beat', 'beater', 'begin', 'bell', 'berries', 'besan',
       'best', 'better', 'beverages', 'bfdbdf', 'bfdbfdbfbr', 'bhaji',
       'binding', 'biscuits', 'bit', 'bite', 'black', 'blend', 'blender',
       'boil', 'boiled', 'boiling', 'boondi', 'bottomed', 'bowl', 'bowls',
       'bread', 'break', 'breakfast', 'briefly', 'bring', 'brinjal',
       'brown', 'browned', 'brush', 'burfy', 'burn', 'butter', 'cabbage',
       'cake', 'capsicum', 'cardamom', 'cardamoms', 'carefully', 'ca

In [182]:
# turns, turning, turn
!pip install nltk

In [274]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()


In [276]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)
recipes["tags"] = recipes["tags"].apply(stem)

In [277]:
new_df["tags"][1]

['Whip',
 'the',
 'cream',
 'till',
 'it',
 'is',
 'fluffy.',
 'Cook',
 'cocoa',
 'powder',
 'in',
 'milk',
 'till',
 'mixed',
 'completely',
 'into',
 'a',
 'smooth',
 'consistency.',
 'Add',
 'Nestlé',
 'MILKMAID,',
 'cooked',
 'cocoa',
 'powder,',
 'vanilla',
 'essence,',
 'whipped',
 'cream',
 '&',
 'mix',
 'well.',
 'Pour',
 'into',
 'a',
 'freezing',
 'tray',
 'and',
 'freeze',
 'till',
 'half',
 'set.',
 'Remove',
 'and',
 'beat',
 'with',
 'a',
 'whisk',
 'or',
 'electric',
 'beater',
 'until',
 'smooth.',
 'Doing',
 'so',
 'will',
 'help',
 'keep',
 'the',
 'texture',
 'of',
 'the',
 'ice',
 'cream',
 'soft',
 'and',
 'creamy',
 'while',
 'it',
 'sets.',
 'our',
 'back',
 'into',
 'tray',
 'and',
 'freeze',
 'till',
 'well',
 'set.',
 'Cocoapowder',
 'whippingcream(cups)',
 'Milk(incup)',
 'brownsugar(incup)']

In [278]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words='english') # 5000 most frequent words

In [279]:
vectors = cv.fit_transform(recipes['tags']).toarray()

In [280]:
print(vectors)
print(vectors[0])
cv.get_feature_names_out() # most frequent names

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  4 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  2  0  0  2  0  4  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  4  0  4  0  0  0  0  0  0  0  0  0  4  0  0  0  0
  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  2  0  0  0  2  4  0  0  0
  0  0  0  0  0  2  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  2  0  0  0  0  0  0  0  2
  0  0  0  0  0  1  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  2  0  0  0  0
  0  0  0  0  0  0  0  0  2  0  4  2  2  0  0  0  0  0  0  0  0  0  0  0
  2 

array(['10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '1½',
       '20', '200', '2½', '30', '450f', '50', '_soda', 'aamchur', 'abl',
       'abov', 'absorb', 'accord', 'achieved', 'ad', 'add', 'adjust',
       'agent', 'al', 'american', 'ani', 'anise', 'anoth', 'apart',
       'appam', 'appe', 'appli', 'approx', 'approxx', 'arhar', 'aroma',
       'aromatic', 'asafoetida', 'asid', 'aside', 'authent', 'away',
       'bake', 'ball', 'balls', 'barfi', 'batch', 'batter', 'bay', 'bean',
       'beat', 'beater', 'becaus', 'becom', 'befor', 'begin', 'bell',
       'berri', 'besan', 'best', 'better', 'beverag', 'bfdbdf',
       'bfdbfdbfbr', 'bhaji', 'bind', 'biscuit', 'bit', 'bite', 'black',
       'blend', 'blender', 'boil', 'boiling', 'boondi', 'bowl', 'bread',
       'break', 'breakfast', 'briefly', 'bring', 'brinjal', 'brown',
       'brush', 'burfi', 'burn', 'butter', 'cabbage', 'cake', 'capsicum',
       'cardamom', 'care', 'carom', 'carrot', 'carrots', 'celeri',
       'ce

In [281]:
from sklearn.metrics.pairwise import cosine_similarity

In [282]:
similarity = cosine_similarity(vectors)

In [283]:
similarity.shape

(19, 19)

In [284]:
similarity[0]

array([1.        , 0.1434442 , 0.27439017, 0.2780404 , 0.40627775,
       0.00817151, 0.18455106, 0.28054938, 0.22691212, 0.15263395,
       0.21763035, 0.32971944, 0.16276482, 0.0553545 , 0.23043821,
       0.01000801, 0.02001602, 0.02001602, 0.01000801])

In [285]:
sorted(list(enumerate(similarity[1])), reverse=True, key=lambda x:x[1])

[(1, 1.0),
 (13, 0.319748523210321),
 (4, 0.1832799783635835),
 (10, 0.16644796441355608),
 (0, 0.14344419642495887),
 (12, 0.12022288792384195),
 (14, 0.10880055640451852),
 (11, 0.09722733743135012),
 (8, 0.09402173859100364),
 (3, 0.0858424882215964),
 (6, 0.08134065697487139),
 (2, 0.07980532478891081),
 (9, 0.06465372136362804),
 (7, 0.06166258370686195),
 (15, 0.03656362120635653),
 (17, 0.03656362120635653),
 (16, 0.018281810603178263),
 (18, 0.018281810603178263),
 (5, 0.014927035850663305)]

In [293]:
list(enumerate(similarity[0]))
def recommend(movie_id):
    movie_index = recipes[recipes["_id"] == movie_id].index[0]
    distances = similarity[movie_index]
    movies_lists = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1: 6]
    for i in movies_lists:
        print(recipes.iloc[i[0]]._id)

In [294]:
recommend("6603b054389c912a6b0655c2")

6603aba5389c912a6b06549d
6603b408389c912a6b065879
66042d3a71b99eea588e0e0b
660435b13563cf7d2fa13a64
66042eba71b99eea588e0e16


In [201]:
new_df[new_df["title"] == "Dabeli"].index

Index([2], dtype='int64')